/*https://music.apple.com/es/artist/neffex/1143134709*/
List<String> getLyrics() {
  return [
    'I got \'em comin at me, all angles',
    'Ever since they heard my music, wanna tangle',
    'I could feel \'em try to grab me by the ankles',
    'I can hear \'em all start to say my name, oh',
    'But it\'s not about the money or the fame, no',
    'No, it\'s all about me just doing my thing, yo',
    '\'cause I\'m loving what I do and I won\'t change, no',
    'I feel blessed, I could do this every day, yo',
    '                                     ',
    'Po-po-pop a couple shots and now I\'m fucked up in the bathroom',
    'Got \'em going off and now they listen like a classroom',
    'Gotta top \'em off because I told them all, they have to',
    'Always poppin\' off the whole squad, gotta pass through',
    'Keep your head high through the hate, yo',
    'Gotta make a better life through the pain, yo',
    'Got a chance to do it right, so do your thing, yo',
    'Don\'t let anybody ever try to change, yo',
    '                            ',
    'I feel blessed, yeah',
    'Yeah, I feel blessed, yeah',
    'I feel blessed, yeah',
    'Yeah, I feel blessed, yeah',
    '                             ',
    'I got \'em comin at me, all angles',
    'Ever since they heard my music, wanna tangle',
    'I could feel \'em try to grab me by the ankles',
    'I can hear \'em all start to say my name, oh',
    'But it\'s not about the money or the fame, no',
    'No, it\'s all about me just doing my thing, yo',
    '\'cause I\'m loving what I do and I won\'t change, no',
    'I feel blessed, I could do this every day, yo',
    '                                         ',
    'Living every day like it\'s my last because you have to',
    'Any given day could be your final chance to act',
    'You got only one life, live it right, don\'t hold back',
    'Do exactly what you like, you gotta fight for your chance',
    'Gotta rest in peace, rest in peace, when you pass',
    'You best believe, best believe I\'ll be the last dude',
    'To ever leave, ever leave, regretting past news',
    'I\'ll never be, never be holding back, truth',
    '                                        ',
    'I feel blessed, yeah',
    'Yeah, I feel blessed, yeah',
    'I feel blessed, yeah',
    'Yeah, I feel blessed, yeah',
  ];
}
